// Generated by https://quicktype.io

export interface AmmosResponse {
    success: boolean;
    count:   number;
    total:   number;
    data:    AmmosData[];
}

export interface AmmosData {
    id:          string;
    name:        string;
    image:       null | string;
    description: string;
    type:        Type | null;
    attackPower: AttackPower[];
    passive:     string;
}

export interface AttackPower {
    name:   Name;
    amount: number | null;
}

export enum Name {
    Critical = "critical",
    Fire = "fire",
    Holy = "holy",
    Lightning = "lightning",
    Magic = "magic",
    Phy100 = "Phy100",
    Phy20 = "Phy20",
    Phy40 = "Phy40",
    Physical = "physical",
}

export enum Type {
    Pierce = "Pierce",
}
