// Generated by https://quicktype.io

export interface BossResponse {
    success: boolean;
    count:   number;
    total:   number;
    data:    BossData[];
}

export interface BossData {
    id:           string;
    name:         string;
    image:        null | string;
    region:       string;
    description:  string;
    location:     string;
    drops:        string[];
    healthPoints: string;
}
