// Generated by https://quicktype.io

export interface CreatureResponse {
    success: boolean;
    count:   number;
    total:   number;
    data:    CreatureData[];
}

export interface CreatureData {
    id:          string;
    name:        string;
    image:       null | string;
    description: null | string;
    location?:   string;
    drops?:      string[];
}
