// Generated by https://quicktype.io

export interface IncantationsResponse {
    success: boolean;
    count:   number;
    total:   number;
    data:    IncantationData[];
}

export interface IncantationData {
    id:          string;
    name:        string;
    image:       null | string;
    description: string;
    type:        Type;
    cost:        number;
    slots:       number;
    effects:     null | string;
    requires:    Require[] | null;
}

export interface Require {
    name:   Name;
    amount: number;
}

export enum Name {
    Arcane = "Arcane",
    Faith = "Faith",
    Intelligence = "Intelligence",
}

export enum Type {
    Incantation = "Incantation",
    Incantations = "Incantations",
}
