// Generated by https://quicktype.io

export interface ItemResponse {
    success: boolean;
    count:   number;
    total:   number;
    data:    ItemData[];
}

export interface ItemData {
    id:            string;
    name:          string;
    image:         null | string;
    description:   null | string;
    type:          Type;
    effect?:       string;
    obtainedFrom?: string;
}

export enum Type {
    CrystalTear = "Crystal Tear",
    CrystalTears = "Crystal Tears",
    Empty = "-",
    InfoItem = "Info Item",
    KeyItem = "Key Item",
    Misc = "Misc",
    None = "None",
    Type = "",
}
