// Generated by https://quicktype.io

export interface ShieldResponse {
    success: boolean;
    count:   number;
    total:   number;
    data:    ShieldData[];
}

export interface ShieldData {
    id:                 string;
    name:               string;
    image:              string;
    description:        string;
    attack:             Attack[];
    defence:            Attack[];
    scalesWith:         ScalesWith[];
    requiredAttributes: Attack[];
    category:           Category | null;
    weight:             number;
}

export interface Attack {
    name:   string;
    amount: number | null;
}

export enum Category {
    Greatshield = "Greatshield",
    MediumShield = "Medium Shield",
    SmallShield = "Small Shield",
    SmallShields = "Small Shields",
}

export interface ScalesWith {
    name:     Name;
    scaling?: Scaling;
}

export enum Name {
    Dex = "Dex",
    Empty = "",
    Fai = "Fai",
    Int = "Int",
    NameINT = "INT",
    NameSTR = "STR",
    Str = "Str",
    Strength = "Strength",
}

export enum Scaling {
    D = "D",
    E = "E",
    Empty = "",
    Purple = "-",
    Scaling = "?",
}
