// Generated by https://quicktype.io

export interface SorceriesResponse {
    success: boolean;
    count:   number;
    total:   number;
    data:    SorceriesData[];
}

export interface SorceriesData {
    id:          string;
    name:        string;
    image:       string;
    description: string;
    type:        Type;
    cost:        number;
    slots:       number;
    effects:     string;
    requires:    Require[];
}

export interface Require {
    name:   Name;
    amount: number;
}

export enum Name {
    Arcane = "Arcane",
    Faith = "Faith",
    Intelligence = "Intelligence",
}

export enum Type {
    Sorceries = "Sorceries",
    Sorcery = "Sorcery",
}
