// Generated by https://quicktype.io

export interface SpiritsResponse {
    success: boolean;
    count:   number;
    total:   number;
    data:    SpiritsData[];
}

export interface SpiritsData {
    id:          string;
    name:        string;
    image:       string;
    description: string;
    fpCost:      string;
    hpCost:      string;
    effect:      string;
}
