// Generated by https://quicktype.io

export interface TalismanResponse {
    success: boolean;
    count:   number;
    total:   number;
    data:    TalismanData[];
}

export interface TalismanData {
    id:          string;
    name:        string;
    image:       string;
    description: string;
    effect:      string;
}
