// Generated by https://quicktype.io

export interface WeaponsResponse {
    success: boolean;
    count:   number;
    total:   number;
    data:    WeaponData[];
}

export interface WeaponData {
    id:                 string;
    name:               string;
    image:              string;
    description:        string;
    attack:             Attack[];
    defence:            Attack[];
    scalesWith:         ScalesWith[];
    requiredAttributes: Attack[];
    category:           string;
    weight:             number;
}

export interface Attack {
    name:   Name;
    amount: number;
}

export enum Name {
    Arc = "Arc",
    Boost = "Boost",
    Crit = "Crit",
    Dex = "Dex",
    EMag = "e\">Mag",
    Empty = "",
    Fai = "Fai",
    Fire = "Fire",
    Holy = "Holy",
    Inc = "Inc",
    Int = "Int",
    Light = "Light",
    Ligt = "Ligt",
    Mag = "Mag",
    NameDEX = "DEX",
    Phy = "Phy",
    Phy120 = "Phy120",
    Rng = "Rng",
    Str = "Str",
}

export interface ScalesWith {
    name:     Name;
    scaling?: Scaling;
}

export enum Scaling {
    B = "B",
    C = "C",
    D = "D",
    E = "E",
    Empty = "?",
}
